---
- name: nginx installation & service started
  hosts: all
  become: true
  tasks:
  - name: install nginx
    REPO: 
        name: nginx
        state: latest 
  - name: service nginx
    service:
        name: nginx
        state: started
